# Generated by Django 3.2.6 on 2022-06-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('picture', models.CharField(max_length=300, null=True)),
                ('details', models.CharField(max_length=5000, null=True)),
            ],
        ),
    ]
