# Generated by Django 3.2.6 on 2022-06-02 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_recipes_picture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipes',
            new_name='Recipe',
        ),
    ]
