# Generated by Django 3.2.6 on 2022-06-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_recipes_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
