# Generated by Django 3.2.6 on 2022-06-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_recipe_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredients',
            new_name='cake',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cream',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
