# Generated by Django 3.2.6 on 2022-06-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_recipe_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='pictures',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
