# Generated by Django 3.2.6 on 2022-06-02 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_recipe_pictures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='pictures',
        ),
    ]
