# Generated by Django 3.2.6 on 2022-06-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_delete_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('cakeIng', models.CharField(max_length=5000, null=True)),
                ('cakePrep', models.CharField(max_length=5000, null=True)),
                ('creamIng', models.CharField(max_length=5000, null=True)),
                ('creamPrep', models.CharField(max_length=5000, null=True)),
            ],
        ),
    ]
