# Generated by Django 3.2.6 on 2022-06-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sales',
            field=models.CharField(max_length=301, null=True),
        ),
    ]
