# Generated by Django 3.2.6 on 2022-06-06 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_product_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sales',
        ),
    ]
