# Generated by Django 3.2.6 on 2022-06-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_product_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alergens',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
