# Generated by Django 3.2.6 on 2022-06-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20220606_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='surname',
            new_name='firstName',
        ),
        migrations.AddField(
            model_name='customer',
            name='lastName',
            field=models.CharField(max_length=301, null=True),
        ),
    ]
