# Generated by Django 3.2.6 on 2022-06-06 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_auto_20220606_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='username',
        ),
    ]
