# Generated by Django 3.2.6 on 2022-06-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_rename_name_customer_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password1',
            field=models.CharField(max_length=301, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='password2',
            field=models.CharField(max_length=301, null=True),
        ),
    ]
