# Generated by Django 3.2.6 on 2022-06-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_auto_20220606_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=301, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(max_length=301, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customer',
            name='street',
            field=models.CharField(max_length=301, null=True),
        ),
    ]
