# Generated by Django 3.2.6 on 2022-06-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_auto_20220607_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='alergens',
            field=models.CharField(choices=[('lactoza', 'lactoza'), ('gluten', 'gluten')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('torturi', 'torturi'), ('briose', 'briose'), ('clatite', 'clatite'), ('pandispan', 'pandispan'), ('prajitura', 'prajitura'), ('biscuiti', 'biscuiti'), ('special', 'special')], max_length=500, null=True),
        ),
    ]
