# Generated by Django 3.2.6 on 2022-06-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_auto_20220608_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in asteptare', 'in asteptare'), ('livrat', 'livrat')], max_length=100, null=True),
        ),
    ]
