# Generated by Django 3.2.6 on 2022-06-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_customer_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
