# Generated by Django 3.2.6 on 2022-06-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_product_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='note',
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(max_length=99999999999999999999, null=True),
        ),
    ]
