# Generated by Django 3.2.6 on 2022-06-10 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_auto_20220609_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='note',
        ),
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
    ]
