# Generated by Django 3.2.6 on 2022-06-14 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='review',
        ),
    ]
