# Generated by Django 3.2.6 on 2022-06-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_alter_product_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revtitle', models.CharField(max_length=300, null=True)),
                ('revmess', models.CharField(max_length=500, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='revmess',
        ),
        migrations.RemoveField(
            model_name='product',
            name='revtitle',
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2),
        ),
    ]
