# Generated by Django 3.2.6 on 2022-06-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_auto_20220614_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='revmess',
        ),
        migrations.RemoveField(
            model_name='product',
            name='revtitle',
        ),
        migrations.AlterField(
            model_name='product',
            name='alergens',
            field=models.CharField(choices=[('lactoza', 'lactoza'), ('gluten', 'gluten')], max_length=500, null=True),
        ),
    ]
