# Generated by Django 3.2.6 on 2022-06-14 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_reviewproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewproduct',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
