# Generated by Django 3.2.6 on 2022-06-14 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_rename_product_reviewproduct_reviewprod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
