# Generated by Django 3.2.6 on 2022-06-23 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0055_recoveremail_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recoveremail',
            name='user',
        ),
    ]
