# Generated by Django 3.2.6 on 2022-06-25 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0056_remove_recoveremail_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
