# Generated by Django 3.2.6 on 2022-06-25 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0057_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewproduct',
            name='reviewProd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product'),
        ),
    ]
