# Generated by Django 3.2.6 on 2022-06-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0059_auto_20220626_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/profil.jpg', upload_to='images/'),
        ),
    ]
