# Generated by Django 3.2.6 on 2022-06-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0066_alter_customer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in asteptare', 'in asteptare'), ('livrat', 'livrat')], default='in asteptare', max_length=100, null=True),
        ),
    ]
